version: '3.4'

services:
    barberizedb:
        container_name: barberizedb
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=BarberizeDB
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - postgres_barberizedb:/var/lib/postgresql/data/
